### ISSUE TITLE
『transmittable thread local 的实现已经有个雏形了』这个表述能调整一下吗？

### ISSUE THREAD

**Issue by oldratlee** [ylgrgyq/ylgrgyq.github.io#3]
https://ylgrgyq.github.io/2017/09/25/transmittable-thread-local/ 文章 很不错！   👍 

文中有这样的表述：

> transmittable thread local 的实现已经有个雏形了

这样的表述会觉得：TTL 是个 玩具的类库（可能这不是你的本意 😄 ）

TTL https://github.com/alibaba/transmittable-thread-local 的实现
是在阿里和其它公司的生产环境上 使用的；中间设计和实现也优化和重构了多个版本。

![image](https://user-images.githubusercontent.com/1063891/33162621-1cce3310-cff0-11e7-9a26-70c5145540c7.png)

#### 比如 调整成

```diff
- 通过上面的描述，transmittable thread local 的实现已经有个雏形了。
+ 通过上面描述的方案可以给出实现的雏形，下面对 transmittable thread local 库的设计和实现简单分析说明如下。
```

**Comment by ylgrgyq** [comment]
哦 抱歉，是我没有表达清楚。我想说的是只是看一下我文章上的描述之后，就对 transmittable thread local 的实现有个大致了解了。我稍后就修改掉。谢谢提醒。

**Comment by oldratlee** [comment]
明白你的意思了。

给力！ 👍 

PS:

1. 如果方便的话，开篇的场景能不以clojure代码的方式说明，方便降低大众的阅读门槛。
1. 我一直没有以易懂的方式来介绍TTL设计和演进，你这篇文章做得很好！ 💟 
我可以加你的文章到我项目首页里作为设计文档的一部分吗？ 😃

**Comment by ylgrgyq** [comment]
Done

**Comment by oldratlee** [comment]
👍 

PS:

1. 如果方便的话，开篇的场景能不以clojure代码的方式说明，方便降低大众的阅读门槛。
1. 我一直没有以易懂的方式来介绍TTL设计和演进，你这篇文章做得很好！ 💟
我可以加你的文章到我项目首页里作为设计文档的一部分吗？ 😃 @ylgrgyq

**Comment by ylgrgyq** [comment]
> 1. 如果方便的话，开篇的场景能不以clojure代码的方式说明，方便降低大众的阅读门槛。

嗯，开篇是有点啰嗦，我想一想怎么描述的更简单一点。

> 我可以加你的文章到我项目首页里作为设计文档的一部分吗？

这个当然没问题，也让我感觉很荣幸。才发现你就是 TTL 库的作者，感谢提供这么好用的库。能想到 TTL 实现点子确实让人敬佩。

**Comment by oldratlee** [comment]
> 开篇是有点啰嗦，我想一想怎么描述的更简单一点。

🆒 

> 这个当然没问题，也让我感觉很荣幸。才发现你就是 TTL 库的作者，感谢提供这么好用的库。能想到 TTL 实现点子确实让人敬佩。

客气了。

有需求了反复想想并持续重构设计，这个库倒也是自然演化出来的 🤣
