### ISSUE TITLE
转载授权

### ISSUE THREAD

**Issue by lyzz0612** [ylgrgyq/ylgrgyq.github.io#5]
遇到相同问题，看到您的博客[一次 TLS SNI 问题](https://ylgrgyq.github.io/2017/04/14/tls-sni/)
大有益处，想要转载收藏，希望得到您的授权。
[转载处](https://blog.csdn.net/lyzz0612/article/details/102821201)
如需额外声明或需要删除麻烦告知谢谢！

**Comment by ylgrgyq** [comment]
很高兴能帮上忙。转载没有问题。
